export const enCopy = {
  title: 'Mixing Studio',
  subtitle: '8-track local stem mixer',
  localOnly: 'LOCAL ONLY',
  status: { idle: 'Idle', ready: 'Loaded', bouncing: 'Bouncing' },
  import: {
    title: 'Tracks',
    dropTitle: 'Drop stems here',
    dropBody: 'Up to 8 tracks, 5:00 each. Audio never leaves this browser.',
    timelineEmpty: 'Loaded stems line up here. Drag a clip to set where each track starts.',
    choose: 'Add tracks',
    loadDemo: 'Load demo',
    demoLow: 'Low band',
    demoHigh: 'High band',
  },
  panels: {
    timeline: 'Arrangement Timeline',
    mixer: '8-Track Mixer',
    inspector: 'Track Inspector',
    master: 'Master',
    export: 'Export',
    help: 'Beginner Guide',
    reverb: 'Reverb Bus',
    groups: 'VCA Groups',
  },
  controls: {
    trim: 'Trim',
    fader: 'Fader',
    pan: 'Pan',
    width: 'Width',
    mute: 'Mute',
    solo: 'Solo',
    polarity: 'Polarity',
    reset: 'Reset',
    remove: 'Remove',
    bounce: 'Bounce Mix',
    download: 'Download WAV',
    exportScene: 'Export Scene',
    importScene: 'Import Scene',
    play: 'Play',
    stop: 'Stop',
    zoom: 'Zoom',
    offset: 'Start',
    panLaw: 'Pan Law',
    panMode: 'Pan Mode',
    dualPanLeft: 'Dual L',
    dualPanRight: 'Dual R',
    channelDelay: 'Delay',
    soloSafe: 'Solo Safe',
    eq: 'Tone EQ',
    eqOn: 'EQ On',
    tilt: 'Tilt',
    air: 'Air',
    reverbSend: 'Reverb Send',
    reverbOn: 'Reverb Bus',
    decay: 'Decay',
    preDelay: 'Pre-Delay',
    vcaGroup: 'VCA Group',
    groupNone: 'None',
    automation: 'Automation',
    curve: 'Curve',
    clearLane: 'Clear Lane',
    automationHint: 'Click the lane to add points; drag to move, double-click to remove.',
  },
  panModes: ['Balance', 'Stereo Pan', 'Dual Pan'],
  panLaws: ['−3 dB', '−4.5 dB', '−6 dB', 'Linear'],
  automationParams: ['Fader', 'Pan', 'Width'],
  automationCurves: ['Linear', 'Exp', 'Hold', 'S-Curve'],
  metrics: {
    duration: 'Duration',
    channels: 'Channels',
    peak: 'Peak',
    rms: 'RMS',
    correlation: 'Correlation',
    sampleRate: 'Sample Rate',
    memory: 'Decoded Memory',
    masterFader: 'Master Fader',
    lufs: 'Integrated LUFS',
    truePeak: 'True Peak',
    monoCompat: 'Mono Compatible',
    goniometer: 'Goniometer',
    yes: 'Yes',
    no: 'Check',
  },
  help: {
    title: 'Start with levels before effects.',
    body: 'Drag clips on the timeline to line up starts, then set faders so no track dominates. Keep the master peak below 0 dBFS, and return from Solo to the full mix before bouncing.',
    docs: 'Open mixing docs',
  },
  progress: { queued: 'Queued', complete: 'Complete' },
  warnings: {
    trackLimit: 'The mixer is limited to 8 tracks.',
    durationLimit: '{file} is longer than 5:00 and was not loaded.',
    memory:
      'This session is using a lot of decoded audio memory. Bounce may be slower on this device.',
    fallback:
      'Realtime DSP is unavailable. Preview is degraded to level and pan; bounce still uses the full mix chain.',
  },
  errors: {
    loadFailed: 'Failed to decode one of the audio files.',
    bounceFailed: 'Mix bounce failed. Try fewer or shorter tracks.',
    sceneFailed: 'Could not import this scene JSON.',
    sceneNoMatch: 'No track settings matched the loaded tracks. Load the matching audio first.',
  },
  stages: {
    'Preparing mix': 'Preparing mix',
    'Loading libsonare WASM': 'Loading libsonare WASM',
    'Preparing tracks': 'Preparing tracks',
    'Applying track settings': 'Applying track settings',
    'Running mixer': 'Running mixer',
    'Applying master fader': 'Applying master fader',
    'Finalizing bounce': 'Finalizing bounce',
  },
  terms: {
    eyebrow: 'Mix Term',
    tipLabel: 'How to use',
    linkLabel: 'Open glossary',
    defaultLabel: 'Default',
    items: {
      trim: {
        title: 'Input Trim',
        body: 'Gain applied before the fader, in dB. Use it to even out clip levels so faders start near unity.',
        tip: 'Set trim first so the loudest moment of each clip sits with healthy headroom, then balance with faders.',
        default: '0 dB',
      },
      fader: {
        title: 'Channel Fader',
        body: 'The main level control for a track, in dB. 0 dB is unity (no change).',
        tip: 'Balance with faders, not trim. Pull dominant tracks down rather than pushing everything up.',
        default: '0 dB',
      },
      masterFader: {
        title: 'Master Fader',
        body: 'Overall output level applied to the summed mix, in dB.',
        tip: 'Leave headroom — aim for the bounce peak to land below 0 dBFS so mastering has room to work.',
        default: '0 dB',
      },
      pan: {
        title: 'Pan',
        body: 'Left–right placement in the stereo field, from −1 (left) to +1 (right).',
        tip: 'Spread elements that compete for the same range; keep bass and lead vocals near center.',
        default: '0 (center)',
      },
      width: {
        title: 'Stereo Width',
        body: 'Scales the stereo spread of a track. 100% is unchanged; 0% collapses it to mono.',
        tip: 'Widen pads and ambience, keep low end narrow. Check correlation after widening.',
        default: '100%',
      },
      polarity: {
        title: 'Polarity Flip',
        body: 'Inverts a channel’s waveform. Used to fix cancellation between mics or stems.',
        tip: 'If combining two tracks makes the low end thinner, try flipping polarity on one of them.',
        default: 'Off',
      },
      correlation: {
        title: 'Stereo Correlation',
        body: 'How alike left and right are, from −1 to +1. +1 is mono, 0 is wide, negative risks phase issues.',
        tip: 'If the bounce sits negative, fold to mono and listen for parts that disappear.',
      },
      lufs: {
        title: 'Integrated LUFS',
        body: 'Loudness of the whole mix, averaged with K-weighting in LUFS. Closer to how loud it actually sounds than peak or RMS.',
        tip: 'Use it to compare overall loudness between mixes; leave final loudness targeting to the mastering stage.',
      },
      truePeak: {
        title: 'True Peak',
        body: 'The highest level between samples (inter-sample peaks), in dBTP. Can exceed the sample peak after conversion to analog or lossy codecs.',
        tip: 'Keep true peak below 0 dBTP — leave around −1 dBTP of headroom for the mastering and encoding stages.',
      },
      monoCompat: {
        title: 'Mono Compatibility',
        body: 'Whether the mix survives a fold to mono without parts cancelling out. Driven by stereo correlation and side energy.',
        tip: 'If it flags, sum to mono and listen for elements that thin out or disappear, then narrow the offending tracks.',
      },
      goniometer: {
        title: 'Goniometer',
        body: 'A vectorscope plotting left against right. A vertical trace is mono, a 45° spread is wide stereo, horizontal smears warn of phase problems.',
        tip: 'Watch for the trace tipping horizontal — that is the same risk the correlation meter reports, shown visually.',
      },
      panLaw: {
        title: 'Pan Law',
        body: 'How much a center-panned signal is attenuated to keep loudness constant as it pans. −3 dB suits uncorrelated stereo; −4.5 dB is a common compromise; −6 dB suits mono sources; Linear applies no compensation.',
        tip: 'Use −3 dB for stereo stems and −4.5/−6 dB for mono sources so panning does not change perceived level.',
        default: '−3 dB',
      },
      panMode: {
        title: 'Pan Mode',
        body: 'Balance shifts the existing left/right level; Stereo Pan repositions a mono-summed signal; Dual Pan places the left and right inputs independently.',
        tip: 'Use Balance for stereo stems, Stereo Pan for mono sources, and Dual Pan to spread or narrow a stereo recording by hand.',
        default: 'Balance',
      },
      dualPan: {
        title: 'Dual Pan',
        body: 'In Dual Pan mode, the left and right input channels get independent positions in the stereo field.',
        tip: 'Pull the two sides inward to narrow a wide stereo stem without collapsing it fully to mono.',
      },
      channelDelay: {
        title: 'Channel Delay',
        body: 'Delays the whole strip by a few milliseconds. Feeds plugin-delay compensation so the mix stays time-aligned.',
        tip: 'Nudge a stem a few ms to fix flammy transients or to align close and room mics.',
        default: '0 ms',
      },
      soloSafe: {
        title: 'Solo Safe',
        body: 'Keeps this track audible even when another track is soloed. Useful for reverb returns and buses.',
        tip: 'Mark effect returns Solo Safe so soloing a dry track still plays its reverb tail.',
        default: 'Off',
      },
      eq: {
        title: 'Tone EQ',
        body: 'A per-strip tone shaper running before the fader: a spectral tilt plus a high-frequency air band.',
        tip: 'Tilt warmer or brighter to seat a track in the mix, then add a little air for sheen.',
        default: 'Off',
      },
      tilt: {
        title: 'Tilt',
        body: 'A spectral tilt pivoting around the midrange, in dB. Negative warms the low end and softens highs; positive brightens.',
        tip: 'Tilt down to tame a harsh track or up to lift a dull one — a fast way to balance overall tone.',
        default: '0 dB',
      },
      air: {
        title: 'Air',
        body: 'A high-frequency shelf (air band), in dB. Adds openness and sparkle up top.',
        tip: 'A touch of air helps vocals and cymbals breathe; too much gets hissy.',
        default: '0 dB',
      },
      reverbSend: {
        title: 'Reverb Send',
        body: 'How much of this track is sent to the shared reverb bus, in dB. Off mutes the send.',
        tip: 'Send several tracks to one reverb for a shared space; keep bass and lead vocals drier.',
        default: 'Off',
      },
      reverb: {
        title: 'Reverb Bus',
        body: 'A shared aux bus with a plate reverb. Tracks feed it via their Reverb Send, and the wet signal returns to the master.',
        tip: 'One reverb for the whole mix glues parts together. Set decay for the room size and pre-delay to keep transients clear.',
        default: 'Off',
      },
      vcaGroup: {
        title: 'VCA Group',
        body: 'Assigns the track to a VCA group. The group fader scales every member’s level together, without changing their relative balance.',
        tip: 'Group drums or backing vocals onto one VCA so you can ride them all with a single fader.',
        default: 'None',
      },
      automation: {
        title: 'Automation',
        body: 'Sample-accurate moves over time for a track’s fader, pan, or width. Each point sets a target value at a moment; the engine interpolates between them.',
        tip: 'Automate the fader to ride a vocal, or pan to sweep an effect. Add points on the lane and choose a curve for the shape between them.',
      },
      curve: {
        title: 'Curve',
        body: 'How the value interpolates between two automation points: Linear is a straight ramp, Exp accelerates, Hold steps, S-Curve eases in and out.',
        tip: 'Use Hold for instant changes, S-Curve for smooth musical moves.',
        default: 'Linear',
      },
      mute: {
        title: 'Mute',
        body: 'Silences this track in the preview and bounce.',
        tip: 'Mute to audition the mix without a part; remember to clear it before bouncing.',
      },
      solo: {
        title: 'Solo',
        body: 'Plays only the soloed track(s), silencing the rest.',
        tip: 'Great for focused edits, but always return to the full mix before judging balance.',
      },
      offset: {
        title: 'Start Offset',
        body: 'Where the clip begins on the timeline, in mm:ss.',
        tip: 'Line up stem starts so transients land together; drag clips on the timeline for coarse moves.',
      },
      peak: {
        title: 'Peak Level',
        body: 'Highest sample amplitude, in dBFS. 0 dBFS is digital full scale.',
        tip: 'Keep the master peak below 0 dBFS to avoid clipping on export.',
      },
      rms: {
        title: 'RMS Level',
        body: 'Average signal energy in dBFS — closer to perceived loudness than peak.',
        tip: 'Compare track RMS values to judge which parts dominate the balance.',
      },
      channels: {
        title: 'Channels',
        body: 'Number of audio channels: 1 is mono, 2 is stereo.',
        tip: 'Mono stems pan cleanly; stereo stems carry their own width.',
      },
      sampleRate: {
        title: 'Sample Rate',
        body: 'Samples captured per second, in Hz — sets the highest reproducible frequency.',
        tip: 'Keep all stems at one rate; mixing mismatched rates can shift pitch and timing.',
      },
      duration: {
        title: 'Duration',
        body: 'Length of the track or mix, in mm:ss.',
        tip: 'The bounce length follows the latest-ending clip on the timeline.',
      },
      memory: {
        title: 'Decoded Memory',
        body: 'Approximate RAM used by decoded audio in this browser session, in MB.',
        tip: 'Large sessions can slow the bounce — remove unused stems if it climbs high.',
      },
    },
  },
};

export const jaCopy: typeof enCopy = {
  title: 'ミキシングスタジオ',
  subtitle: '8 トラックのローカルステムミキサー',
  localOnly: 'LOCAL ONLY',
  status: { idle: '待機中', ready: '読み込み済み', bouncing: 'バウンス中' },
  import: {
    title: 'トラック',
    dropTitle: 'ステムをドロップ',
    dropBody: '最大 8 トラック、各 5:00 まで。音声はブラウザ内だけで処理されます。',
    timelineEmpty:
      '読み込んだステムがここに並びます。クリップをドラッグして各トラックの開始位置を合わせます。',
    choose: 'トラックを追加',
    loadDemo: 'デモを読み込む',
    demoLow: '低域',
    demoHigh: '高域',
  },
  panels: {
    timeline: 'アレンジタイムライン',
    mixer: '8 トラックミキサー',
    inspector: 'トラック詳細',
    master: 'マスター',
    export: '書き出し',
    help: '初心者ガイド',
    reverb: 'リバーブバス',
    groups: 'VCA グループ',
  },
  controls: {
    trim: 'トリム',
    fader: 'フェーダー',
    pan: 'パン',
    width: '幅',
    mute: 'ミュート',
    solo: 'ソロ',
    polarity: '極性',
    reset: 'リセット',
    remove: '削除',
    bounce: 'ミックスをバウンス',
    download: 'WAV を保存',
    exportScene: 'シーンを書き出し',
    importScene: 'シーンを読み込み',
    play: '再生',
    stop: '停止',
    zoom: 'ズーム',
    offset: '開始',
    panLaw: 'パンの法則',
    panMode: 'パンモード',
    dualPanLeft: 'デュアル L',
    dualPanRight: 'デュアル R',
    channelDelay: 'ディレイ',
    soloSafe: 'ソロセーフ',
    eq: 'トーン EQ',
    eqOn: 'EQ オン',
    tilt: 'ティルト',
    air: 'エア',
    reverbSend: 'リバーブ送り',
    reverbOn: 'リバーブバス',
    decay: 'ディケイ',
    preDelay: 'プリディレイ',
    vcaGroup: 'VCA グループ',
    groupNone: 'なし',
    automation: 'オートメーション',
    curve: 'カーブ',
    clearLane: 'レーンを消去',
    automationHint: 'レーンをクリックして点を追加、ドラッグで移動、ダブルクリックで削除します。',
  },
  panModes: ['バランス', 'ステレオパン', 'デュアルパン'],
  panLaws: ['−3 dB', '−4.5 dB', '−6 dB', 'リニア'],
  automationParams: ['フェーダー', 'パン', '幅'],
  automationCurves: ['リニア', '指数', 'ホールド', 'S字'],
  metrics: {
    duration: '長さ',
    channels: 'チャンネル',
    peak: 'ピーク',
    rms: 'RMS',
    correlation: '相関',
    sampleRate: 'サンプルレート',
    memory: 'デコード後メモリ',
    masterFader: 'マスターフェーダー',
    lufs: '統合 LUFS',
    truePeak: 'トゥルーピーク',
    monoCompat: 'モノラル互換',
    goniometer: 'ゴニオメーター',
    yes: '良好',
    no: '要確認',
  },
  help: {
    title: 'まずエフェクトより音量バランスです。',
    body: 'タイムライン上のクリップをドラッグして開始位置をそろえ、フェーダーで各トラックの主張を整えます。マスターのピークを 0 dBFS 未満に保ち、Solo の確認後は必ず全体で聴いてからバウンスしてください。',
    docs: 'ミキシング資料を開く',
  },
  progress: { queued: '待機中', complete: '完了' },
  warnings: {
    trackLimit: 'このミキサーは 8 トラックまでです。',
    durationLimit: '{file} は 5:00 を超えているため読み込みませんでした。',
    memory:
      'デコード済み音声メモリが大きくなっています。この端末ではバウンスに時間がかかる場合があります。',
    fallback:
      'リアルタイム DSP を利用できないため、プレビューは音量とパンのみです。バウンスには完全なミックスチェーンを使用します。',
  },
  errors: {
    loadFailed: '音声ファイルのデコードに失敗しました。',
    bounceFailed: 'ミックスのバウンスに失敗しました。トラック数や長さを減らしてください。',
    sceneFailed: 'このシーン JSON を読み込めませんでした。',
    sceneNoMatch:
      '読み込み済みのトラックに一致する設定がありませんでした。先に対応する音源を読み込んでください。',
  },
  stages: {
    'Preparing mix': 'ミックスを準備中',
    'Loading libsonare WASM': 'libsonare WASM を読み込み中',
    'Preparing tracks': 'トラックを準備中',
    'Applying track settings': 'トラック設定を適用中',
    'Running mixer': 'ミキサーを実行中',
    'Applying master fader': 'マスターフェーダーを適用中',
    'Finalizing bounce': 'バウンスを仕上げ中',
  },
  terms: {
    eyebrow: 'ミックス用語',
    tipLabel: '使い方',
    linkLabel: '用語集を開く',
    defaultLabel: '初期値',
    items: {
      trim: {
        title: '入力トリム',
        body: 'フェーダーの前段で加えるゲイン（dB）。各クリップのレベルをそろえ、フェーダーをユニティ付近から始められるようにします。',
        tip: 'まずトリムで各クリップの最大音量に十分なヘッドルームを確保し、その後フェーダーでバランスを取ります。',
        default: '0 dB',
      },
      fader: {
        title: 'チャンネルフェーダー',
        body: 'トラックの主音量コントロール（dB）。0 dB がユニティ（変化なし）です。',
        tip: 'トリムではなくフェーダーでバランスを取ります。全体を上げるより、目立つトラックを下げましょう。',
        default: '0 dB',
      },
      masterFader: {
        title: 'マスターフェーダー',
        body: 'ミックス合算後の全体出力レベル（dB）です。',
        tip: 'ヘッドルームを残し、バウンスのピークが 0 dBFS 未満に収まるようにすると、マスタリングに余地が生まれます。',
        default: '0 dB',
      },
      pan: {
        title: 'パン',
        body: 'ステレオ内の左右位置。−1（左）〜+1（右）で表します。',
        tip: '同じ帯域で競合する音を左右に振り分け、低音とリードボーカルは中央付近に保ちます。',
        default: '0（中央）',
      },
      width: {
        title: 'ステレオ幅',
        body: 'トラックのステレオ広がりを調整します。100% は変化なし、0% でモノラルになります。',
        tip: 'パッドや空間系は広げ、低域は狭く保ちます。広げた後は相関を確認してください。',
        default: '100%',
      },
      polarity: {
        title: '極性反転',
        body: 'チャンネルの波形を反転します。マイクやステム間の打ち消しを直すのに使います。',
        tip: '2 つのトラックを合わせて低域が痩せる場合は、片方の極性を反転してみてください。',
        default: 'オフ',
      },
      correlation: {
        title: 'ステレオ相関',
        body: '左右の類似度を −1〜+1 で表します。+1 はモノラル、0 は広がり、負の値は位相の問題を招きます。',
        tip: 'バウンスが負の値なら、モノラルに畳んで消える音がないか確認してください。',
      },
      lufs: {
        title: '統合 LUFS',
        body: 'K特性で平均したミックス全体のラウドネス（LUFS）。ピークや RMS より実際の聴感の大きさに近い指標です。',
        tip: 'ミックス間の全体的な音量比較に使います。最終的なラウドネス調整はマスタリング工程に任せましょう。',
      },
      truePeak: {
        title: 'トゥルーピーク',
        body: 'サンプル間（インターサンプル）を含む最大レベル（dBTP）。アナログ変換や非可逆コーデック後にサンプルピークを超えることがあります。',
        tip: 'トゥルーピークは 0 dBTP 未満に保ち、マスタリングやエンコードのために −1 dBTP 程度の余裕を残します。',
      },
      monoCompat: {
        title: 'モノラル互換性',
        body: 'モノラルに畳んだときに音が打ち消し合わず残るかどうか。ステレオ相関とサイド成分のエネルギーから判定します。',
        tip: '警告が出たらモノラルに合算し、痩せたり消えたりする音を探して、該当トラックの幅を狭めてください。',
      },
      goniometer: {
        title: 'ゴニオメーター',
        body: '左右を縦横にプロットするベクトルスコープ。縦の軌跡はモノラル、45° の広がりは広いステレオ、水平な広がりは位相問題の警告です。',
        tip: '軌跡が水平に倒れていないか確認します。相関メーターが示す危険を視覚的に表したものです。',
      },
      panLaw: {
        title: 'パンの法則',
        body: 'センター定位の信号を、パン時に音量が一定に保たれるようどれだけ減衰させるか。−3 dB は無相関ステレオ向け、−4.5 dB は一般的な妥協値、−6 dB はモノラル音源向け、リニアは補正なしです。',
        tip: 'ステレオステムには −3 dB、モノラル音源には −4.5／−6 dB を使うと、パンしても体感上の音量が変わりません。',
        default: '−3 dB',
      },
      panMode: {
        title: 'パンモード',
        body: 'バランスは既存の左右レベルを振り、ステレオパンはモノ合算した信号を定位し、デュアルパンは左右の入力を個別に配置します。',
        tip: 'ステレオステムはバランス、モノラル音源はステレオパン、ステレオ録音を手動で広げ／狭めたいときはデュアルパンを使います。',
        default: 'バランス',
      },
      dualPan: {
        title: 'デュアルパン',
        body: 'デュアルパンモードでは、左右の入力チャンネルをステレオ内で個別に定位できます。',
        tip: '左右を内側に寄せると、完全にモノラルへ畳まずに広いステレオステムを狭められます。',
      },
      channelDelay: {
        title: 'チャンネルディレイ',
        body: 'ストリップ全体を数ミリ秒遅らせます。プラグインディレイ補正に渡され、ミックスの時間整合を保ちます。',
        tip: '数 ms ずらしてトランジェントのよれを直したり、オンマイクと部屋マイクをそろえたりします。',
        default: '0 ms',
      },
      soloSafe: {
        title: 'ソロセーフ',
        body: '他のトラックをソロにしても、このトラックを鳴らし続けます。リバーブリターンやバスに便利です。',
        tip: 'エフェクトリターンをソロセーフにすると、ドライなトラックをソロにしてもリバーブの残響が鳴ります。',
        default: 'オフ',
      },
      eq: {
        title: 'トーン EQ',
        body: 'フェーダー前で動くストリップごとの音色調整。スペクトルティルトと高域のエアバンドを備えます。',
        tip: 'ティルトで暖かく／明るく整えてトラックをミックスになじませ、必要ならエアでツヤを足します。',
        default: 'オフ',
      },
      tilt: {
        title: 'ティルト',
        body: '中域を支点に傾けるスペクトルティルト（dB）。マイナスは低域を暖かくし高域を抑え、プラスは明るくします。',
        tip: '耳に痛いトラックは下げ、こもったトラックは上げます。全体の音色を素早く整える方法です。',
        default: '0 dB',
      },
      air: {
        title: 'エア',
        body: '高域のシェルフ（エアバンド、dB）。上の帯域に抜けときらめきを加えます。',
        tip: '少しのエアでボーカルやシンバルが息づきます。上げすぎるとシャリつきます。',
        default: '0 dB',
      },
      reverbSend: {
        title: 'リバーブ送り',
        body: 'このトラックを共有リバーブバスへ送る量（dB）。オフで送りを止めます。',
        tip: '複数トラックを1つのリバーブに送ると共通の空間にまとまります。低音やリードボーカルは控えめに。',
        default: 'オフ',
      },
      reverb: {
        title: 'リバーブバス',
        body: 'プレートリバーブを持つ共有 AUX バス。各トラックはリバーブ送りで信号を送り、ウェット成分がマスターに戻ります。',
        tip: '1つのリバーブで全体をまとめると一体感が出ます。ディケイで部屋の広さを、プリディレイでトランジェントの明瞭さを調整します。',
        default: 'オフ',
      },
      vcaGroup: {
        title: 'VCA グループ',
        body: 'トラックを VCA グループに割り当てます。グループフェーダーは相対バランスを保ったまま、全メンバーの音量をまとめて上下させます。',
        tip: 'ドラムやコーラスを1つの VCA にまとめると、1本のフェーダーで全体を操作できます。',
        default: 'なし',
      },
      automation: {
        title: 'オートメーション',
        body: 'トラックのフェーダー・パン・幅を時間に沿ってサンプル精度で動かします。各点はある時点の目標値を表し、エンジンが点と点の間を補間します。',
        tip: 'フェーダーを自動化してボーカルを追ったり、パンでエフェクトを左右に振ったり。レーンに点を追加し、間の形をカーブで選びます。',
      },
      curve: {
        title: 'カーブ',
        body: '2点間の補間の仕方。リニアは直線、指数は加速、ホールドは段階的、S字は緩やかに入って緩やかに出ます。',
        tip: '瞬時の変化にはホールド、滑らかな音楽的な動きには S字を使います。',
        default: 'リニア',
      },
      mute: {
        title: 'ミュート',
        body: 'このトラックをプレビューとバウンスで無音にします。',
        tip: 'パートを外して試聴するのに使います。バウンス前に解除を忘れずに。',
      },
      solo: {
        title: 'ソロ',
        body: 'ソロにしたトラックだけを再生し、他を無音にします。',
        tip: '集中して編集するのに便利ですが、バランス判断の前に必ず全体へ戻してください。',
      },
      offset: {
        title: '開始オフセット',
        body: 'タイムライン上でクリップが始まる位置（mm:ss）です。',
        tip: 'ステムの開始をそろえてトランジェントを合わせます。大まかな移動はタイムラインのドラッグで行えます。',
      },
      peak: {
        title: 'ピークレベル',
        body: '最大サンプル振幅（dBFS）。0 dBFS がデジタルのフルスケールです。',
        tip: '書き出しでクリップしないよう、マスターのピークを 0 dBFS 未満に保ちます。',
      },
      rms: {
        title: 'RMS レベル',
        body: '信号の平均エネルギー（dBFS）。ピークより知覚ラウドネスに近い指標です。',
        tip: 'トラックごとの RMS を比べると、どのパートがバランスを支配しているか判断できます。',
      },
      channels: {
        title: 'チャンネル数',
        body: '音声のチャンネル数。1 はモノラル、2 はステレオです。',
        tip: 'モノラルのステムはきれいにパンでき、ステレオのステムは自前の広がりを持ちます。',
      },
      sampleRate: {
        title: 'サンプルレート',
        body: '1 秒あたりのサンプル数（Hz）。再生できる最高周波数を決めます。',
        tip: 'すべてのステムを同じレートにそろえてください。異なるレートを混ぜると音程やタイミングがずれます。',
      },
      duration: {
        title: '長さ',
        body: 'トラックまたはミックスの長さ（mm:ss）です。',
        tip: 'バウンスの長さは、タイムラインで最も遅く終わるクリップに合わせられます。',
      },
      memory: {
        title: 'デコード後メモリ',
        body: 'このブラウザセッションでデコード済み音声が使うおおよその RAM（MB）です。',
        tip: 'セッションが大きいとバウンスが遅くなります。増えてきたら未使用のステムを削除してください。',
      },
    },
  },
};
