export const enCopy = {
  title: 'Music Analysis Studio',
  subtitle: 'Structure, harmony, loudness, and spectrum analysis',
  localOnly: 'LOCAL ONLY',
  docs: 'Docs',
  status: {
    idle: 'Idle',
    ready: 'Loaded',
    analyzing: 'Analyzing',
  },
  import: {
    title: 'Source',
    dropTitle: 'Drop audio here',
    dropBody: 'WAV, MP3, FLAC, OGG. Audio stays in this browser.',
    choose: 'Choose file',
    demo: 'Load demo',
    analyzing: 'Analyzing...',
  },
  progress: {
    queued: 'Queued',
    decoding: 'Decoding audio',
    complete: 'Complete',
  },
  panels: {
    overview: 'Overview',
    timeline: 'Structure Timeline',
    loudness: 'Loudness Timeline',
    spectrum: 'Matrix Views',
    harmony: 'Harmony',
    melody: 'Melody',
    source: 'Source Metrics',
    help: 'How to read this',
  },
  loudness: {
    momentary: 'Momentary',
    shortTerm: 'Short-term',
    integrated: 'Integrated',
  },
  metrics: {
    bpm: 'BPM',
    bpmConfidence: 'Tempo Conf.',
    key: 'Key',
    keyConfidence: 'Key Conf.',
    time: 'Meter',
    lufs: 'LUFS',
    lra: 'LRA',
    dynamicRange: 'Dyn. Range',
    crest: 'Crest',
    brightness: 'Brightness',
    warmth: 'Warmth',
    peak: 'Peak',
    rms: 'RMS',
    correlation: 'Correlation',
    confidence: 'Confidence',
    pitchRange: 'Pitch Range',
    pitchStability: 'Pitch Stability',
    meanPitch: 'Mean Pitch',
    vibrato: 'Vibrato',
  },
  timeline: {
    confidence: 'Confidence',
    energy: 'Energy',
  },
  heatmaps: {
    chroma: 'Chroma',
    mel: 'Mel',
    cqt: 'CQT',
  },
  help: {
    title: 'Analysis is evidence, not a verdict.',
    body: 'Use confidence, section boundaries, and the spectrogram together. If key or chord confidence is low, inspect the chroma view and listen around section changes before making arrangement or mastering decisions.',
    docs: 'Open analysis docs',
  },
  actions: {
    export: 'Export JSON report',
    rerun: 'Run again',
  },
  empty: {
    title: 'No analysis yet',
    body: 'Load a track to generate structure, harmony, melody, loudness, and spectrum views.',
    timeline: 'Sections, chords, and beats appear here.',
    spectrum: 'Chroma, mel, and CQT heatmaps appear here.',
    harmony: 'Key and scale candidates appear here.',
    melody: 'Pitch range, stability, and vibrato appear here.',
  },
  warnings: {
    longFile: 'Large files can take time on this device. The analysis still runs locally.',
  },
  errors: {
    loadFailed: 'Failed to decode this audio file.',
    analysisFailed: 'Analysis failed. Try a shorter file or reload the page.',
    demoFailed: 'Failed to load demo audio.',
  },
  stages: {
    'Preparing audio': 'Preparing audio',
    'Optimizing long file': 'Optimizing long file',
    'Loading libsonare WASM': 'Loading libsonare WASM',
    'Running musical analysis': 'Running musical analysis',
    'Finding alternate keys': 'Finding alternate keys',
    'Detecting downbeats and sections': 'Detecting downbeats and sections',
    'Tracing melody': 'Tracing melody',
    'Measuring loudness': 'Measuring loudness',
    'Computing chroma': 'Computing chroma',
    'Computing mel spectrogram': 'Computing mel spectrogram',
    'Computing CQT': 'Computing CQT',
    'Finalizing report': 'Finalizing report',
  },
  terms: {
    eyebrow: 'MIR Term',
    tipLabel: 'How to read',
    linkLabel: 'Open glossary',
    items: {
      bpm: {
        title: 'Tempo · BPM',
        body: 'Beats per minute — the estimated pulse of the track. Higher values feel faster.',
        tip: 'Cross-check against the beat markers on the timeline; halved or doubled estimates are a common detection slip.',
      },
      key: {
        title: 'Musical Key',
        body: 'The estimated tonal center and mode (major / minor) the music settles around.',
        tip: 'When confidence is low, treat it as a hint and confirm by ear over a stable section.',
      },
      keyConfidence: {
        title: 'Key Confidence',
        body: 'How strongly the chroma evidence supports the detected key, from 0 to 100%.',
        tip: 'Below ~50% the harmony is ambiguous — open the chroma view before trusting the key.',
      },
      time: {
        title: 'Time Signature',
        body: 'The detected meter, e.g. 4/4 — how many beats are grouped into one bar.',
        tip: 'Most pop is 4/4 and waltz-like material is 3/4. Verify against the downbeat markers.',
      },
      lufs: {
        title: 'Integrated LUFS',
        body: 'Perceived loudness over the whole track, weighted for human hearing. Streaming usually targets around −14 LUFS.',
        tip: 'Compare it to your delivery target instead of chasing an absolute number.',
      },
      lra: {
        title: 'Loudness Range · LRA',
        body: 'The spread between the quiet and loud passages, measured in LU. Larger means more dynamic contrast.',
        tip: 'Very low LRA can signal over-compression; very high can feel uneven on small speakers.',
      },
      dynamicRange: {
        title: 'Dynamic Range',
        body: 'Distance between the loudest peaks and the average level, in dB.',
        tip: 'Genre-dependent: acoustic keeps it wide, dense EDM tends to run narrow.',
      },
      crest: {
        title: 'Crest Factor',
        body: 'Peak-to-RMS ratio in dB. High crest means punchy transients; low crest means a dense, limited sound.',
        tip: 'Watch it fall as you compress or limit — it quantifies how much punch you trade away.',
      },
      brightness: {
        title: 'Brightness',
        body: 'Relative weight of high-frequency energy in the timbre, from 0 to 1. Higher reads as airy or sharp.',
        tip: 'Compare sections: a brighter chorus often just has more cymbals or open vocals, not a different mix.',
      },
      warmth: {
        title: 'Warmth',
        body: 'Relative weight of low-mid energy in the timbre, from 0 to 1. Higher reads as full or rounded.',
        tip: 'Read it against brightness to gauge tonal balance before reaching for an EQ.',
      },
      momentary: {
        title: 'Momentary LUFS',
        body: 'Loudness over a 400 ms sliding window, tracked across the whole track.',
        tip: 'The spiky line — watch it peak during the loudest hits to spot where a limiter will work hardest.',
      },
      shortTerm: {
        title: 'Short-term LUFS',
        body: 'Loudness over a 3 s sliding window — a smoother view of how loudness moves between sections.',
        tip: 'Use it to compare verse vs chorus loudness; large jumps map to the structure timeline above.',
      },
      peak: {
        title: 'Peak Level',
        body: 'The highest sample amplitude, in dBFS. 0 dBFS is digital full scale.',
        tip: 'Keep headroom below 0 dBFS so later stages and lossy codecs do not clip.',
      },
      rms: {
        title: 'RMS Level',
        body: 'Average signal energy in dBFS — closer to perceived loudness than peak.',
        tip: 'Read it alongside peak to judge how dense the material is.',
      },
      correlation: {
        title: 'Stereo Correlation',
        body: 'How alike the left and right channels are, from −1 to +1. +1 is mono, 0 is wide, negative risks phase problems.',
        tip: 'If it sits negative, check mono compatibility before any mastering decision.',
      },
      pitchRange: {
        title: 'Pitch Range',
        body: 'The span of the traced melody, in octaves.',
        tip: 'A wide range suggests an expressive lead; a narrow one suggests a chant or rap.',
      },
      pitchStability: {
        title: 'Pitch Stability',
        body: 'How steady the detected melody pitch is, from 0 to 100%.',
        tip: 'Low stability often means breathy, slid, or polyphonic material the tracer struggles with.',
      },
      meanPitch: {
        title: 'Mean Pitch',
        body: 'Average fundamental frequency of the melody, in Hz.',
        tip: 'As a rule of thumb 220 Hz ≈ A3 — use it to place the lead register.',
      },
      vibrato: {
        title: 'Vibrato Rate',
        body: 'Speed of pitch oscillation in the melody, in Hz.',
        tip: 'Typical sung vibrato is 5–7 Hz; near 0 means flat, sustained notes.',
      },
      chroma: {
        title: 'Chroma',
        body: 'Energy folded into the 12 pitch classes, so harmony shows regardless of octave.',
        tip: 'Use it to sanity-check the key and to spot where chords change.',
      },
      mel: {
        title: 'Mel Spectrogram',
        body: 'The spectrum on a perceptual (mel) frequency scale over time.',
        tip: 'Good for seeing timbre and brightness shift between sections.',
      },
      cqt: {
        title: 'Constant-Q Transform',
        body: 'A spectrum with log-spaced bins aligned to musical pitches.',
        tip: 'Reads bass notes and harmony better than a linear FFT.',
      },
    },
  },
};

export const jaCopy: typeof enCopy = {
  title: '楽曲分析スタジオ',
  subtitle: '構成、ハーモニー、ラウドネス、スペクトルを分析',
  localOnly: 'LOCAL ONLY',
  docs: '資料',
  status: {
    idle: '待機中',
    ready: '読み込み済み',
    analyzing: '解析中',
  },
  import: {
    title: '音源',
    dropTitle: '音声をドロップ',
    dropBody: 'WAV、MP3、FLAC、OGG 対応。音声はブラウザ内だけで処理されます。',
    choose: 'ファイルを選択',
    demo: 'デモを読み込む',
    analyzing: '解析中...',
  },
  progress: {
    queued: '待機中',
    decoding: '音声をデコード中',
    complete: '完了',
  },
  panels: {
    overview: '概要',
    timeline: '構成タイムライン',
    loudness: 'ラウドネス推移',
    spectrum: 'マトリクス表示',
    harmony: 'ハーモニー',
    melody: 'メロディ',
    source: '音源指標',
    help: '読み方',
  },
  loudness: {
    momentary: 'モーメンタリ',
    shortTerm: '短期',
    integrated: '統合',
  },
  metrics: {
    bpm: 'BPM',
    bpmConfidence: 'テンポ信頼度',
    key: 'キー',
    keyConfidence: 'キー信頼度',
    time: '拍子',
    lufs: 'LUFS',
    lra: 'LRA',
    dynamicRange: 'ダイナミックレンジ',
    crest: 'クレスト',
    brightness: '明るさ',
    warmth: '温かさ',
    peak: 'ピーク',
    rms: 'RMS',
    correlation: '相関',
    confidence: '信頼度',
    pitchRange: '音域',
    pitchStability: 'ピッチ安定度',
    meanPitch: '平均ピッチ',
    vibrato: 'ビブラート',
  },
  timeline: {
    confidence: '信頼度',
    energy: 'エネルギー',
  },
  heatmaps: {
    chroma: 'クロマ',
    mel: 'Mel',
    cqt: 'CQT',
  },
  help: {
    title: '解析結果は結論ではなく判断材料です。',
    body: '信頼度、セクション境界、スペクトログラムを合わせて見ます。キーやコードの信頼度が低い場合は、セクション変化付近を聴きながらクロマ表示も確認してください。',
    docs: '解析ドキュメントを開く',
  },
  actions: {
    export: 'JSON レポートを書き出す',
    rerun: '再解析',
  },
  empty: {
    title: 'まだ解析結果がありません',
    body: '音源を読み込むと、構成、ハーモニー、メロディ、ラウドネス、スペクトルを表示します。',
    timeline: 'セクション・コード・ビートがここに表示されます。',
    spectrum: 'クロマ／メル／CQT のヒートマップがここに表示されます。',
    harmony: 'キーとスケールの候補がここに表示されます。',
    melody: 'ピッチレンジ・安定度・ビブラートがここに表示されます。',
  },
  warnings: {
    longFile:
      '大きなファイルはこの端末で時間がかかる場合があります。解析はローカルで実行されます。',
  },
  errors: {
    loadFailed: 'この音声ファイルをデコードできませんでした。',
    analysisFailed: '解析に失敗しました。短いファイルを試すかページを再読み込みしてください。',
    demoFailed: 'デモ音源を読み込めませんでした。',
  },
  stages: {
    'Preparing audio': '音声を準備中',
    'Optimizing long file': '長いファイル向けに最適化中',
    'Loading libsonare WASM': 'libsonare WASM を読み込み中',
    'Running musical analysis': '楽曲解析を実行中',
    'Finding alternate keys': '別候補のキーを探索中',
    'Detecting downbeats and sections': 'ダウンビートとセクションを検出中',
    'Tracing melody': 'メロディを追跡中',
    'Measuring loudness': 'ラウドネスを測定中',
    'Computing chroma': 'クロマを計算中',
    'Computing mel spectrogram': 'メルスペクトログラムを計算中',
    'Computing CQT': 'CQT を計算中',
    'Finalizing report': 'レポートを仕上げ中',
  },
  terms: {
    eyebrow: 'MIR 用語',
    tipLabel: '読み方',
    linkLabel: '用語集を開く',
    items: {
      bpm: {
        title: 'テンポ · BPM',
        body: '1 分あたりの拍数。曲の推定テンポで、値が大きいほど速く感じます。',
        tip: 'タイムラインのビートマーカーと照合してください。半分や倍に誤検出されることがよくあります。',
      },
      key: {
        title: 'キー（調）',
        body: '曲が落ち着く中心音と旋法（メジャー／マイナー）の推定です。',
        tip: '信頼度が低いときはヒント程度に扱い、安定した区間で耳でも確認してください。',
      },
      keyConfidence: {
        title: 'キー信頼度',
        body: 'クロマの根拠が検出キーをどれだけ支持しているかを 0〜100% で示します。',
        tip: '50% を下回るとハーモニーが曖昧です。キーを信頼する前にクロマ表示を確認してください。',
      },
      time: {
        title: '拍子',
        body: '検出した拍子（例: 4/4）。1小節に何拍をまとめるかを表します。',
        tip: 'ポップスの多くは 4/4、ワルツ系は 3/4 です。ダウンビートのマーカーで確認してください。',
      },
      lufs: {
        title: '統合ラウドネス（LUFS）',
        body: '人間の聴感に合わせて重み付けした、曲全体の知覚ラウドネスです。配信は概ね −14 LUFS が目安です。',
        tip: '絶対値を追うのではなく、配信先のターゲットと比較してください。',
      },
      lra: {
        title: 'ラウドネスレンジ（LRA）',
        body: '静かな部分と大きな部分の差を LU で表します。大きいほどダイナミクスの幅が広いことを意味します。',
        tip: 'LRA が極端に小さいと過圧縮の兆候、大きすぎると小型スピーカーでムラに感じることがあります。',
      },
      dynamicRange: {
        title: 'ダイナミックレンジ',
        body: '最大ピークと平均レベルの差を dB で表します。',
        tip: 'ジャンル依存です。アコースティックは広く、密度の高い EDM は狭くなりがちです。',
      },
      crest: {
        title: 'クレストファクター',
        body: 'ピークと RMS の比（dB）。値が大きいほど打撃感のあるトランジェント、小さいほど密で抑え込まれた音になります。',
        tip: 'コンプやリミッターで下がっていきます。失われる打撃感を数値で確認できます。',
      },
      brightness: {
        title: '明るさ',
        body: '音色に占める高域エネルギーの相対量を 0〜1 で表します。高いほど空気感のある、または鋭い印象になります。',
        tip: '区間で比較してみてください。サビが明るいのは多くの場合シンバルや開いたボーカルが増えただけで、ミックスの違いとは限りません。',
      },
      warmth: {
        title: '温かさ',
        body: '音色に占める中低域エネルギーの相対量を 0〜1 で表します。高いほど太く、丸い印象になります。',
        tip: '明るさと並べて見ると、EQ に手を伸ばす前に音色バランスを把握できます。',
      },
      momentary: {
        title: 'モーメンタリ LUFS',
        body: '400 ms のスライディング窓によるラウドネスを、曲全体にわたって追跡します。',
        tip: 'とがった線です。最も大きい打撃でどこまで跳ねるかを見ると、リミッターが最も働く箇所が分かります。',
      },
      shortTerm: {
        title: 'ショートターム LUFS',
        body: '3 秒のスライディング窓によるラウドネスで、区間ごとのラウドネスの動きをなめらかに見られます。',
        tip: 'ヴァースとサビのラウドネス比較に使えます。大きな段差は上の構成タイムラインと対応します。',
      },
      peak: {
        title: 'ピークレベル',
        body: '最大サンプル振幅（dBFS）。0 dBFS がデジタルのフルスケールです。',
        tip: '後段の処理や非可逆コーデックでクリップしないよう、0 dBFS 未満のヘッドルームを残してください。',
      },
      rms: {
        title: 'RMS レベル',
        body: '信号の平均エネルギー（dBFS）。ピークより知覚ラウドネスに近い指標です。',
        tip: 'ピークと併せて見ると、素材の密度を判断できます。',
      },
      correlation: {
        title: 'ステレオ相関',
        body: '左右チャンネルの類似度を −1〜+1 で表します。+1 はモノラル、0 は広がり、負の値は位相の問題を招きます。',
        tip: '負の値のときは、マスタリングの判断前にモノラル互換性を確認してください。',
      },
      pitchRange: {
        title: '音域',
        body: '抽出したメロディの音域をオクターブ単位で表します。',
        tip: '広ければ表現豊かなリード、狭ければ語りやラップを示唆します。',
      },
      pitchStability: {
        title: 'ピッチ安定度',
        body: '検出したメロディのピッチがどれだけ安定しているかを 0〜100% で表します。',
        tip: '安定度が低いのは、息成分・しゃくり・複数音などで追跡が難しい素材であることが多いです。',
      },
      meanPitch: {
        title: '平均ピッチ',
        body: 'メロディの基本周波数の平均（Hz）です。',
        tip: '目安として 220 Hz ≒ A3。リードの音域を把握するのに使えます。',
      },
      vibrato: {
        title: 'ビブラート速度',
        body: 'メロディのピッチ揺れの速さ（Hz）です。',
        tip: '歌唱のビブラートは概ね 5〜7 Hz。0 付近はまっすぐ伸ばした音を意味します。',
      },
      chroma: {
        title: 'クロマ',
        body: 'エネルギーを12の音名クラスに畳み込み、オクターブによらずハーモニーを表示します。',
        tip: 'キーの妥当性確認や、コードの変わり目を見つけるのに使えます。',
      },
      mel: {
        title: 'メルスペクトログラム',
        body: '聴感に沿ったメル周波数スケールで、スペクトルの時間変化を表示します。',
        tip: '区間ごとの音色や明るさの変化を見るのに向いています。',
      },
      cqt: {
        title: '定数 Q 変換（CQT）',
        body: '音律に合わせて対数間隔で並んだビンを持つスペクトルです。',
        tip: '線形 FFT より低音やハーモニーが読みやすくなります。',
      },
    },
  },
};
