/**
 * Physical-layer grouping for the tuner's model-parameter knobs. A physical
 * model is a signal chain of distinct layers — the exciter that injects energy,
 * the resonator that vibrates, the secondary paths coupled to it, the body that
 * radiates, and the articulation that shapes the gesture. The flat `*PatchParams`
 * struct hides this, so we group each scalar/bool field under the layer it drives
 * to make "which layer, which parameter" legible. Assignment is grounded in each
 * voice core's field semantics, not a generic textbook split.
 */
import type { PhysicalEngineMode } from '@/tuner/dsp/params';

/** The physical layers, in signal-flow order. */
export type LayerId = 'exciter' | 'resonator' | 'coupling' | 'body' | 'dynamics';

/** Layers in the order the signal flows through them. */
export const LAYER_ORDER: LayerId[] = ['exciter', 'resonator', 'coupling', 'body', 'dynamics'];

/**
 * Per-engine map from a `*PatchParams` scalar/bool field to its physical layer.
 * Non-scalar fields (mode/rank tables) are edited separately and omitted here.
 */
export const PARAM_LAYER: Record<PhysicalEngineMode, Record<string, LayerId>> = {
  'karplus-strong': {
    pickPosition: 'exciter',
    excBrightness: 'exciter',
    pluckStyle: 'exciter',
    nail: 'exciter',
    brightness: 'resonator',
    decayS: 'resonator',
    decayStretch: 'resonator',
    slap: 'resonator',
    dispersion: 'resonator',
    tensionMod: 'resonator',
    polarization: 'coupling',
    bodyCoupling: 'coupling',
    sympathetic: 'coupling',
    octaveMix: 'coupling',
    pickupPos: 'body',
    velToBrightness: 'dynamics',
    releaseDampS: 'dynamics',
    keyoffNoise: 'dynamics',
  },
  modal: {
    strikeBrightness: 'exciter',
    numModes: 'resonator',
    decayS: 'resonator',
    decayStretch: 'resonator',
    velToBrightness: 'dynamics',
    releaseDampS: 'dynamics',
  },
  'bowed-string': {
    bowPosition: 'exciter',
    bowForce: 'exciter',
    bowSpeed: 'exciter',
    rosin: 'exciter',
    elastoPlastic: 'exciter',
    stribeck: 'exciter',
    brightness: 'resonator',
    damping: 'resonator',
    sympathetic: 'coupling',
    polarization: 'coupling',
    velToSpeed: 'dynamics',
    attackMs: 'dynamics',
    releaseMs: 'dynamics',
  },
  reed: {
    breathPressure: 'exciter',
    reedStiffness: 'exciter',
    reedOpening: 'exciter',
    breathNoise: 'exciter',
    dynamicReed: 'exciter',
    reedResonance: 'exciter',
    conical: 'resonator',
    brightness: 'resonator',
    damping: 'resonator',
    coneGrowth: 'resonator',
    registerVent: 'coupling',
    tonehole: 'coupling',
    velToBreath: 'dynamics',
    attackMs: 'dynamics',
    releaseMs: 'dynamics',
    chiff: 'dynamics',
    chiffMs: 'dynamics',
    growl: 'dynamics',
  },
  brass: {
    breathPressure: 'exciter',
    lipTension: 'exciter',
    lipDamping: 'exciter',
    breathNoise: 'exciter',
    dynamicLip: 'exciter',
    conical: 'resonator',
    brightness: 'resonator',
    damping: 'resonator',
    halfValve: 'resonator',
    brassiness: 'body',
    mute: 'body',
    velToBreath: 'dynamics',
    attackMs: 'dynamics',
    releaseMs: 'dynamics',
    chiff: 'dynamics',
    chiffMs: 'dynamics',
    cuivreDynamics: 'dynamics',
  },
  flute: {
    breathPressure: 'exciter',
    jetRatio: 'exciter',
    jetReflection: 'exciter',
    breathNoise: 'exciter',
    overblow: 'exciter',
    jetTurbulence: 'exciter',
    edgeHysteresis: 'exciter',
    vortex: 'exciter',
    endReflection: 'resonator',
    brightness: 'resonator',
    damping: 'resonator',
    velToBreath: 'dynamics',
    attackMs: 'dynamics',
    releaseMs: 'dynamics',
    chiff: 'dynamics',
    chiffMs: 'dynamics',
    vibratoRateHz: 'dynamics',
    vibratoDepth: 'dynamics',
  },
  piano: {
    strikePosition: 'exciter',
    hammerExponent: 'exciter',
    hammerContactMs: 'exciter',
    decayFastS: 'resonator',
    decaySlowS: 'resonator',
    decayStretch: 'resonator',
    brightness: 'resonator',
    dispersion: 'resonator',
    strings: 'coupling',
    detuneCents: 'coupling',
    soundboard: 'body',
    hammerDynamics: 'dynamics',
    releaseDampS: 'dynamics',
  },
  'pipe-organ': {
    breath: 'exciter',
    reed: 'exciter',
    stopped: 'resonator',
    brightness: 'resonator',
    toneDecayS: 'resonator',
    rankCount: 'coupling',
    keytrack: 'coupling',
    radiation: 'body',
    swell: 'body',
    chiff: 'dynamics',
    chiffMs: 'dynamics',
    releaseDampS: 'dynamics',
    tremulantRateHz: 'dynamics',
    tremulantDepth: 'dynamics',
    windSag: 'dynamics',
  },
  'plucked-string': {
    pickPosition: 'exciter',
    excBrightness: 'exciter',
    brightness: 'resonator',
    decayS: 'resonator',
    decayStretch: 'resonator',
    buzz: 'coupling',
    velToBrightness: 'dynamics',
    releaseDampS: 'dynamics',
  },
  vocal: {
    brightness: 'exciter',
    breathNoise: 'exciter',
    vowel: 'resonator',
    vibratoRateHz: 'dynamics',
    vibratoDepth: 'dynamics',
    attackMs: 'dynamics',
    releaseMs: 'dynamics',
  },
  'free-reed': {
    breathPressure: 'exciter',
    reedStiffness: 'exciter',
    breathNoise: 'exciter',
    detune: 'coupling',
    brightness: 'body',
    velToBreath: 'dynamics',
    attackMs: 'dynamics',
    releaseMs: 'dynamics',
  },
  percussion: {
    strikeR: 'exciter',
    strikeTheta: 'exciter',
    noiseGain: 'exciter',
    noiseDecayMs: 'exciter',
    noiseCutoffHz: 'exciter',
    noiseQ: 'exciter',
    noiseOutput: 'exciter',
    phisemBeans: 'exciter',
    phisemEnergyMs: 'exciter',
    phisemSoundMs: 'exciter',
    phisemScrapeHz: 'exciter',
    numModes: 'resonator',
    modeDecayS: 'resonator',
    toneGain: 'resonator',
    baseFreqHz: 'resonator',
    pitchDrop: 'resonator',
    pitchDropMs: 'resonator',
    phisemResHz: 'resonator',
    phisemResQ: 'resonator',
    phisemPitchGlide: 'resonator',
    wireBuzz: 'coupling',
    wireThreshold: 'coupling',
    wireCutoffHz: 'coupling',
    shimmer: 'coupling',
    shimmerAttackMs: 'coupling',
    shimmerCutoffHz: 'coupling',
    shellMix: 'body',
    shellNumModes: 'body',
    gmKit: 'dynamics',
    exclusiveClass: 'dynamics',
  },
};

/** The physical layer a param belongs to (resonator is the neutral fallback). */
export function layerOf(engine: PhysicalEngineMode, key: string): LayerId {
  return PARAM_LAYER[engine]?.[key] ?? 'resonator';
}
