/**
 * Japanese and English names for the GS insertion-effect types.
 *
 * This table is shared by the GS module and embedded inline demos. Keeping it
 * below src/utils prevents one demo's registry from importing another demo.
 */

import type { LocalizedName } from './modelNames';

/** The standard name for each GS insertion-effect type, keyed by two-byte hex. */
export const GS_EFX_TYPES: Readonly<Record<string, LocalizedName>> = {
  '00 00': { en: 'Thru', ja: 'スルー' },
  '01 00': { en: 'Stereo-EQ', ja: 'ステレオ EQ' },
  '01 01': { en: 'Spectrum', ja: 'スペクトラム' },
  '01 02': { en: 'Enhancer', ja: 'エンハンサー' },
  '01 03': { en: 'Humanizer', ja: 'ヒューマナイザー' },
  '01 10': { en: 'Overdrive', ja: 'オーバードライブ' },
  '01 11': { en: 'Distortion', ja: 'ディストーション' },
  '01 20': { en: 'Phaser', ja: 'フェイザー' },
  '01 21': { en: 'Auto Wah', ja: 'オートワウ' },
  '01 22': { en: 'Rotary', ja: 'ロータリー' },
  '01 23': { en: 'Stereo Flanger', ja: 'ステレオフランジャー' },
  '01 24': { en: 'Step Flanger', ja: 'ステップフランジャー' },
  '01 25': { en: 'Tremolo', ja: 'トレモロ' },
  '01 26': { en: 'Auto Pan', ja: 'オートパン' },
  '01 30': { en: 'Compressor', ja: 'コンプレッサー' },
  '01 31': { en: 'Limiter', ja: 'リミッター' },
  '01 40': { en: 'Hexa Chorus', ja: 'ヘキサコーラス' },
  '01 41': { en: 'Tremolo Chorus', ja: 'トレモロコーラス' },
  '01 42': { en: 'Stereo Chorus', ja: 'ステレオコーラス' },
  '01 43': { en: 'Space-D', ja: 'スペース D' },
  '01 44': { en: '3D Chorus', ja: '3D コーラス' },
  '01 50': { en: 'Stereo Delay', ja: 'ステレオディレイ' },
  '01 51': { en: 'Modulation Delay', ja: 'モジュレーションディレイ' },
  '01 52': { en: '3 Tap Delay', ja: '3 タップディレイ' },
  '01 53': { en: '4 Tap Delay', ja: '4 タップディレイ' },
  '01 54': { en: 'Time Control Delay', ja: 'タイムコントロールディレイ' },
  '01 55': { en: 'Reverb', ja: 'リバーブ' },
  '01 56': { en: 'Gate Reverb', ja: 'ゲートリバーブ' },
  '01 57': { en: '3D Delay', ja: '3D ディレイ' },
  '01 60': { en: '2-Voice Pitch Shifter', ja: '2 ボイスピッチシフター' },
  '01 61': { en: 'Feedback Pitch Shifter', ja: 'フィードバックピッチシフター' },
  '01 70': { en: '3D Auto', ja: '3D オート' },
  '01 71': { en: '3D Manual', ja: '3D マニュアル' },
  '01 72': { en: 'Lo-Fi 1', ja: 'ローファイ 1' },
  '01 73': { en: 'Lo-Fi 2', ja: 'ローファイ 2' },
  '02 00': { en: 'Overdrive → Chorus', ja: 'オーバードライブ → コーラス' },
  '02 01': { en: 'Overdrive → Flanger', ja: 'オーバードライブ → フランジャー' },
  '02 02': { en: 'Overdrive → Delay', ja: 'オーバードライブ → ディレイ' },
  '02 03': { en: 'Distortion → Chorus', ja: 'ディストーション → コーラス' },
  '02 04': { en: 'Distortion → Flanger', ja: 'ディストーション → フランジャー' },
  '02 05': { en: 'Distortion → Delay', ja: 'ディストーション → ディレイ' },
  '02 06': { en: 'Enhancer → Chorus', ja: 'エンハンサー → コーラス' },
  '02 07': { en: 'Enhancer → Flanger', ja: 'エンハンサー → フランジャー' },
  '02 08': { en: 'Enhancer → Delay', ja: 'エンハンサー → ディレイ' },
  '02 09': { en: 'Chorus → Delay', ja: 'コーラス → ディレイ' },
  '02 0A': { en: 'Flanger → Delay', ja: 'フランジャー → ディレイ' },
  '02 0B': { en: 'Chorus → Flanger', ja: 'コーラス → フランジャー' },
  '03 00': { en: 'Rotary Multi', ja: 'ロータリーマルチ' },
  '04 00': { en: 'Guitar Multi 1', ja: 'ギターマルチ 1' },
  '04 01': { en: 'Guitar Multi 2', ja: 'ギターマルチ 2' },
  '04 02': { en: 'Guitar Multi 3', ja: 'ギターマルチ 3' },
  '04 03': { en: 'Clean Guitar Multi 1', ja: 'クリーンギターマルチ 1' },
  '04 04': { en: 'Clean Guitar Multi 2', ja: 'クリーンギターマルチ 2' },
  '04 05': { en: 'Bass Multi', ja: 'ベースマルチ' },
  '04 06': { en: 'Rhodes Multi', ja: 'ローズマルチ' },
  '05 00': { en: 'Keyboard Multi', ja: 'キーボードマルチ' },
  '11 00': { en: 'Chorus/Delay', ja: 'コーラス / ディレイ' },
  '11 01': { en: 'Flanger/Delay', ja: 'フランジャー / ディレイ' },
  '11 02': { en: 'Chorus/Flanger', ja: 'コーラス / フランジャー' },
  '11 03': { en: 'Overdrive/Distortion 1, 2', ja: 'オーバードライブ / ディストーション 1、2' },
  '11 04': {
    en: 'Overdrive/Distortion, Rotary',
    ja: 'オーバードライブ / ディストーション、ロータリー',
  },
  '11 05': {
    en: 'Overdrive/Distortion, Phaser',
    ja: 'オーバードライブ / ディストーション、フェイザー',
  },
  '11 06': {
    en: 'Overdrive/Distortion, Auto Wah',
    ja: 'オーバードライブ / ディストーション、オートワウ',
  },
  '11 07': { en: 'Phaser, Rotary', ja: 'フェイザー、ロータリー' },
  '11 08': { en: 'Phaser, Auto Wah', ja: 'フェイザー、オートワウ' },
};
