import type { enCopy } from '@/components/mixing/mixingCopy';

export type MixingTermKey = keyof typeof enCopy.terms.items;

export const MIXING_TERM_SLUGS: Record<MixingTermKey, string | undefined> = {
  trim: 'concepts/gain-staging',
  fader: 'concepts/gain-staging',
  masterFader: 'concepts/gain-staging',
  pan: 'concepts/audio-basics',
  width: 'concepts/mono-compatibility',
  polarity: 'concepts/mono-compatibility',
  correlation: 'concepts/mono-compatibility',
  lufs: 'concepts/loudness-matching',
  truePeak: 'concepts/true-peak-safety',
  monoCompat: 'concepts/mono-compatibility',
  goniometer: 'concepts/mono-compatibility',
  panLaw: 'concepts/mixing-basics',
  panMode: 'concepts/mixing-basics',
  dualPan: 'concepts/mixing-basics',
  channelDelay: 'concepts/mixing-basics',
  soloSafe: undefined,
  eq: 'concepts/mixing-basics',
  tilt: 'concepts/mixing-basics',
  air: 'concepts/mixing-basics',
  reverbSend: 'concepts/mixing-basics',
  reverb: 'concepts/mixing-basics',
  vcaGroup: 'concepts/mixing-basics',
  automation: 'concepts/mixing-basics',
  curve: 'concepts/mixing-basics',
  mute: undefined,
  solo: undefined,
  offset: undefined,
  peak: 'concepts/audio-basics',
  rms: 'concepts/audio-basics',
  channels: 'concepts/audio-basics',
  sampleRate: 'concepts/audio-basics',
  duration: undefined,
  memory: 'concepts/browser-local-processing',
};
