export const enCopy = {
  title: 'Realtime FX Lab',
  subtitle: 'Mic input voice changer and speaker output',
  localOnly: 'LOCAL ONLY',
  status: { idle: 'Idle', starting: 'Starting', ready: 'Ready', monitoring: 'Speaker on' },
  panels: {
    input: 'Input',
    presets: 'Presets',
    voice: 'Voice',
    meters: 'Meters',
    safety: 'Speaker Safety',
  },
  presets: {
    natural: {
      label: 'Natural',
      hint: 'Subtle blend that keeps your real voice with a touch of space.',
    },
    low: { label: 'Low', hint: 'Drops pitch and formant for a deeper, larger voice.' },
    bright: { label: 'Bright', hint: 'Lifts pitch and formant for a smaller, brighter voice.' },
    robot: { label: 'Robot', hint: 'Heavy ring-mod buzz for a vocoder-like robot tone.' },
    room: { label: 'Room', hint: 'Adds a small room ambience around a natural voice.' },
    hall: { label: 'Hall', hint: 'Long hall reflections for a spacious, distant voice.' },
  },
  actions: {
    start: 'Start engine',
    stop: 'Stop',
    monitorOn: 'Speaker on',
    monitorOff: 'Speaker off',
  },
  controls: {
    pitch: 'Pitch',
    formant: 'Formant',
    wet: 'Wet/Dry',
    robot: 'Robot',
    reverb: 'Ambience',
    output: 'Output',
    bypass: 'Bypass',
  },
  metrics: {
    inputPeak: 'Input Peak',
    outputPeak: 'Output Peak',
    inputRms: 'Input RMS',
    outputRms: 'Output RMS',
    latency: 'Latency',
    clip: 'Output clipped — click to reset',
  },
  help: { docs: 'Open realtime docs' },
  safety: {
    title: 'Use headphones before turning speakers on.',
    body: 'The microphone is routed to your default browser output. Speakers can feed back into the mic and become loud quickly. Speaker output starts off by default.',
  },
  errors: {
    noMicApi: 'This browser does not expose microphone input.',
    startFailed: 'Could not start the realtime audio engine.',
  },
  terms: {
    eyebrow: 'FX Term',
    tipLabel: 'How to use',
    linkLabel: 'Open glossary',
    defaultLabel: 'Default',
    items: {
      pitch: {
        title: 'Pitch Shift',
        body: 'Moves the voice up or down in semitones without changing its speed. 12 st is one octave.',
        tip: 'Small shifts (±2 st) stay natural; large shifts read as an effect. Pair with formant to keep it believable.',
        default: '0 st',
      },
      formant: {
        title: 'Formant',
        body: 'Scales the resonances that define vocal character, shifting the perceived size of the singer.',
        tip: 'Below 1 sounds larger / deeper, above 1 sounds smaller / brighter. Adjust opposite to pitch for a natural shift.',
        default: '1.00',
      },
      wet: {
        title: 'Wet / Dry',
        body: 'Balance between the processed (wet) signal and the untouched (dry) input.',
        tip: 'Blend in dry signal to keep intelligibility when effects get heavy.',
        default: '55%',
      },
      robot: {
        title: 'Robot',
        body: 'Forces the voice onto a fixed pitched buzz for a vocoder-like robotic tone.',
        tip: 'Push it up for a clear robot effect; keep it low to just add a metallic edge.',
        default: '0%',
      },
      reverb: {
        title: 'Ambience',
        body: 'Adds simulated room reflections so the voice sits in a space rather than sounding dry.',
        tip: 'A little adds depth; too much smears consonants and pushes the voice back.',
        default: '15%',
      },
      output: {
        title: 'Output Gain',
        body: 'Final level applied before speaker output, as a percentage of unity.',
        tip: 'Trim it down if the output meter is hitting the top; loud speaker output risks feedback.',
        default: '70%',
      },
      bypass: {
        title: 'Bypass',
        body: 'Passes the dry microphone straight through, skipping all effects.',
        tip: 'Toggle it to A/B the processed voice against the raw input.',
      },
      inputPeak: {
        title: 'Input Peak',
        body: 'Loudest incoming mic level, in dBFS. 0 dBFS is digital full scale.',
        tip: 'Keep peaks below 0 dBFS — back off the mic or input if it pins to the top.',
      },
      outputPeak: {
        title: 'Output Peak',
        body: 'Loudest processed level sent to your speaker output, in dBFS.',
        tip: 'Lower the output gain if this approaches 0 dBFS to avoid clipping and feedback.',
      },
      inputRms: {
        title: 'Input RMS',
        body: 'Average incoming mic energy in dBFS — closer to perceived loudness than peak.',
        tip: 'Aim for a steady RMS while speaking; large swings make effects react unevenly.',
      },
      outputRms: {
        title: 'Output RMS',
        body: 'Average processed energy in dBFS sent to your speaker output.',
        tip: 'Compare with input RMS to see how much the effects change perceived level.',
      },
      latency: {
        title: 'Latency',
        body: 'Round-trip delay between mic input and speaker output, in milliseconds.',
        tip: 'Lower is better for live output. Browser and device buffers set the floor here.',
      },
    },
  },
};

export const jaCopy: typeof enCopy = {
  title: 'リアルタイム FX ラボ',
  subtitle: 'マイク入力のボイスチェンジャーとスピーカー出力',
  localOnly: 'LOCAL ONLY',
  status: { idle: '待機中', starting: '起動中', ready: '準備完了', monitoring: 'スピーカー出力中' },
  panels: {
    input: '入力',
    presets: 'プリセット',
    voice: 'ボイス',
    meters: 'メーター',
    safety: 'スピーカー安全性',
  },
  presets: {
    natural: { label: 'ナチュラル', hint: '素の声を保ちつつ、わずかに空間を加えるバランス設定。' },
    low: { label: 'ロー', hint: 'ピッチとフォルマントを下げ、深く大きい声に。' },
    bright: { label: 'ブライト', hint: 'ピッチとフォルマントを上げ、小さく明るい声に。' },
    robot: { label: 'ロボット', hint: '強いリングモジュレーションでボコーダー風のロボット声に。' },
    room: { label: 'ルーム', hint: '自然な声に小さな部屋のアンビエンスを加える。' },
    hall: { label: 'ホール', hint: '長いホールの反射で、広く遠い空間の声に。' },
  },
  actions: {
    start: 'エンジン開始',
    stop: '停止',
    monitorOn: 'スピーカー ON',
    monitorOff: 'スピーカー OFF',
  },
  controls: {
    pitch: 'ピッチ',
    formant: 'フォルマント',
    wet: 'Wet/Dry',
    robot: 'ロボット',
    reverb: 'アンビエンス',
    output: '出力',
    bypass: 'バイパス',
  },
  metrics: {
    inputPeak: '入力ピーク',
    outputPeak: '出力ピーク',
    inputRms: '入力 RMS',
    outputRms: '出力 RMS',
    latency: 'レイテンシ',
    clip: '出力クリップ — クリックでリセット',
  },
  help: { docs: 'リアルタイム資料を開く' },
  safety: {
    title: 'スピーカーを ON にする前にヘッドホンを使ってください。',
    body: 'マイク音声はブラウザの既定出力へ戻ります。スピーカー出力はマイクへ回り込み、急に大きなハウリングになる場合があります。初期状態ではスピーカー OFF です。',
  },
  errors: {
    noMicApi: 'このブラウザではマイク入力を利用できません。',
    startFailed: 'リアルタイム音声エンジンを開始できませんでした。',
  },
  terms: {
    eyebrow: 'FX 用語',
    tipLabel: '使い方',
    linkLabel: '用語集を開く',
    defaultLabel: '初期値',
    items: {
      pitch: {
        title: 'ピッチシフト',
        body: '速度を変えずに声を半音単位で上下させます。12 st が 1 オクターブです。',
        tip: '±2 st 程度なら自然に保てます。大きく動かすと効果音的になります。フォルマントと組み合わせると自然さを保てます。',
        default: '0 st',
      },
      formant: {
        title: 'フォルマント',
        body: '声のキャラクターを決める共鳴を伸縮させ、話者の体格感を変えます。',
        tip: '1 より下で大きく低く、上で小さく明るく聞こえます。ピッチと逆方向に動かすと自然なシフトになります。',
        default: '1.00',
      },
      wet: {
        title: 'Wet / Dry',
        body: '処理後（Wet）の信号と、未処理（Dry）の入力とのバランスです。',
        tip: 'エフェクトが強いときは Dry を混ぜると明瞭度を保てます。',
        default: '55%',
      },
      robot: {
        title: 'ロボット',
        body: '声を固定ピッチのブザーに乗せ、ボコーダーのようなロボット声にします。',
        tip: '上げるとはっきりロボット化し、低めにすると金属的な質感を少し加える程度になります。',
        default: '0%',
      },
      reverb: {
        title: '空間（アンビエンス）',
        body: '部屋の反射をシミュレートし、ドライではなく空間の中にいる声にします。',
        tip: '少量で奥行きが出ます。かけすぎると子音がにじみ、声が後ろに下がります。',
        default: '15%',
      },
      output: {
        title: '出力ゲイン',
        body: 'スピーカー出力前に加える最終レベル（ユニティに対する割合）です。',
        tip: '出力メーターが上限に当たるなら下げてください。大音量のスピーカー出力はハウリングの原因になります。',
        default: '70%',
      },
      bypass: {
        title: 'バイパス',
        body: 'すべてのエフェクトを飛ばし、ドライのマイク音をそのまま通します。',
        tip: '切り替えて、処理後の声と素の入力を A/B 比較できます。',
      },
      inputPeak: {
        title: '入力ピーク',
        body: '入ってくるマイクの最大レベル（dBFS）。0 dBFS がデジタルのフルスケールです。',
        tip: 'ピークは 0 dBFS 未満に保ちます。上限に張り付くならマイクや入力を下げてください。',
      },
      outputPeak: {
        title: '出力ピーク',
        body: 'スピーカーへ送る処理後の最大レベル（dBFS）です。',
        tip: '0 dBFS に近づいたら出力ゲインを下げ、クリップやハウリングを防ぎます。',
      },
      inputRms: {
        title: '入力 RMS',
        body: '入ってくるマイクの平均エネルギー（dBFS）。ピークより知覚ラウドネスに近い指標です。',
        tip: '話している間は RMS を安定させます。変動が大きいとエフェクトの反応がムラになります。',
      },
      outputRms: {
        title: '出力 RMS',
        body: 'スピーカーへ送る処理後の平均エネルギー（dBFS）です。',
        tip: '入力 RMS と比べると、エフェクトが体感レベルをどれだけ変えたか分かります。',
      },
      latency: {
        title: 'レイテンシ',
        body: 'マイク入力からスピーカー出力までの往復遅延（ミリ秒）です。',
        tip: 'ライブ出力では小さいほど有利です。ブラウザと端末のバッファが下限を決めます。',
      },
    },
  },
};
