/**
 * Bilingual names for the GM instrument set and the GS insertion-effect types,
 * for the module demo's labels rather than the engine itself.
 *
 * `GS_EFX_TYPES` is keyed by the same two-byte hex spelling as
 * `data/efx-tables.json`'s `defaults.by_type`, so the demo can look a type's
 * name up by the exact key the data file already carries. Every one of that
 * file's 65 keys has a confirmed name here; there is nothing to list in
 * {@link GS_EFX_TYPES_UNNAMED}.
 */

/** A display name in both languages the site serves. */
export interface LocalizedName {
  en: string;
  ja: string;
}

export const GM_FAMILIES: readonly { first: number; last: number; name: LocalizedName }[] = [
  { first: 0, last: 7, name: { en: 'Piano', ja: 'ピアノ' } },
  { first: 8, last: 15, name: { en: 'Chromatic Percussion', ja: 'クロマチックパーカッション' } },
  { first: 16, last: 23, name: { en: 'Organ', ja: 'オルガン' } },
  { first: 24, last: 31, name: { en: 'Guitar', ja: 'ギター' } },
  { first: 32, last: 39, name: { en: 'Bass', ja: 'ベース' } },
  { first: 40, last: 47, name: { en: 'Strings', ja: 'ストリングス' } },
  { first: 48, last: 55, name: { en: 'Ensemble', ja: 'アンサンブル' } },
  { first: 56, last: 63, name: { en: 'Brass', ja: 'ブラス' } },
  { first: 64, last: 71, name: { en: 'Reed', ja: 'リード' } },
  { first: 72, last: 79, name: { en: 'Pipe', ja: 'パイプ' } },
  { first: 80, last: 87, name: { en: 'Synth Lead', ja: 'シンセリード' } },
  { first: 88, last: 95, name: { en: 'Synth Pad', ja: 'シンセパッド' } },
  { first: 96, last: 103, name: { en: 'Synth Effects', ja: 'シンセエフェクト' } },
  { first: 104, last: 111, name: { en: 'Ethnic', ja: 'エスニック' } },
  { first: 112, last: 119, name: { en: 'Percussive', ja: 'パーカッション' } },
  { first: 120, last: 127, name: { en: 'Sound Effects', ja: 'サウンドエフェクト' } },
];

/** The General MIDI Level 1 sound set, index = program number. */
export const GM_PROGRAMS: readonly LocalizedName[] = [
  { en: 'Acoustic Grand Piano', ja: 'アコースティックグランドピアノ' },
  { en: 'Bright Acoustic Piano', ja: 'ブライトアコースティックピアノ' },
  { en: 'Electric Grand Piano', ja: 'エレクトリックグランドピアノ' },
  { en: 'Honky-tonk Piano', ja: 'ホンキートンクピアノ' },
  { en: 'Electric Piano 1', ja: 'エレクトリックピアノ 1' },
  { en: 'Electric Piano 2', ja: 'エレクトリックピアノ 2' },
  { en: 'Harpsichord', ja: 'ハープシコード' },
  { en: 'Clavinet', ja: 'クラビネット' },
  { en: 'Celesta', ja: 'チェレスタ' },
  { en: 'Glockenspiel', ja: 'グロッケンシュピール' },
  { en: 'Music Box', ja: 'ミュージックボックス' },
  { en: 'Vibraphone', ja: 'ビブラフォン' },
  { en: 'Marimba', ja: 'マリンバ' },
  { en: 'Xylophone', ja: 'シロフォン' },
  { en: 'Tubular Bells', ja: 'チューブラーベル' },
  { en: 'Dulcimer', ja: 'ダルシマー' },
  { en: 'Drawbar Organ', ja: 'ドローバーオルガン' },
  { en: 'Percussive Organ', ja: 'パーカッシブオルガン' },
  { en: 'Rock Organ', ja: 'ロックオルガン' },
  { en: 'Church Organ', ja: 'チャーチオルガン' },
  { en: 'Reed Organ', ja: 'リードオルガン' },
  { en: 'Accordion', ja: 'アコーディオン' },
  { en: 'Harmonica', ja: 'ハーモニカ' },
  { en: 'Tango Accordion', ja: 'タンゴアコーディオン' },
  { en: 'Acoustic Guitar (nylon)', ja: 'アコースティックギター（ナイロン）' },
  { en: 'Acoustic Guitar (steel)', ja: 'アコースティックギター（スチール）' },
  { en: 'Electric Guitar (jazz)', ja: 'エレキギター（ジャズ）' },
  { en: 'Electric Guitar (clean)', ja: 'エレキギター（クリーン）' },
  { en: 'Electric Guitar (muted)', ja: 'エレキギター（ミュート）' },
  { en: 'Overdriven Guitar', ja: 'オーバードライブギター' },
  { en: 'Distortion Guitar', ja: 'ディストーションギター' },
  { en: 'Guitar Harmonics', ja: 'ギターハーモニクス' },
  { en: 'Acoustic Bass', ja: 'アコースティックベース' },
  { en: 'Electric Bass (finger)', ja: 'エレキベース（フィンガー）' },
  { en: 'Electric Bass (pick)', ja: 'エレキベース（ピック）' },
  { en: 'Fretless Bass', ja: 'フレットレスベース' },
  { en: 'Slap Bass 1', ja: 'スラップベース 1' },
  { en: 'Slap Bass 2', ja: 'スラップベース 2' },
  { en: 'Synth Bass 1', ja: 'シンセベース 1' },
  { en: 'Synth Bass 2', ja: 'シンセベース 2' },
  { en: 'Violin', ja: 'バイオリン' },
  { en: 'Viola', ja: 'ビオラ' },
  { en: 'Cello', ja: 'チェロ' },
  { en: 'Contrabass', ja: 'コントラバス' },
  { en: 'Tremolo Strings', ja: 'トレモロストリングス' },
  { en: 'Pizzicato Strings', ja: 'ピチカートストリングス' },
  { en: 'Orchestral Harp', ja: 'オーケストラルハープ' },
  { en: 'Timpani', ja: 'ティンパニ' },
  { en: 'String Ensemble 1', ja: 'ストリングアンサンブル 1' },
  { en: 'String Ensemble 2', ja: 'ストリングアンサンブル 2' },
  { en: 'Synth Strings 1', ja: 'シンセストリングス 1' },
  { en: 'Synth Strings 2', ja: 'シンセストリングス 2' },
  { en: 'Choir Aahs', ja: 'クワイア（アー）' },
  { en: 'Voice Oohs', ja: 'ボイス（ウー）' },
  { en: 'Synth Voice', ja: 'シンセボイス' },
  { en: 'Orchestra Hit', ja: 'オーケストラヒット' },
  { en: 'Trumpet', ja: 'トランペット' },
  { en: 'Trombone', ja: 'トロンボーン' },
  { en: 'Tuba', ja: 'チューバ' },
  { en: 'Muted Trumpet', ja: 'ミュートトランペット' },
  { en: 'French Horn', ja: 'フレンチホルン' },
  { en: 'Brass Section', ja: 'ブラスセクション' },
  { en: 'Synth Brass 1', ja: 'シンセブラス 1' },
  { en: 'Synth Brass 2', ja: 'シンセブラス 2' },
  { en: 'Soprano Sax', ja: 'ソプラノサックス' },
  { en: 'Alto Sax', ja: 'アルトサックス' },
  { en: 'Tenor Sax', ja: 'テナーサックス' },
  { en: 'Baritone Sax', ja: 'バリトンサックス' },
  { en: 'Oboe', ja: 'オーボエ' },
  { en: 'English Horn', ja: 'イングリッシュホルン' },
  { en: 'Bassoon', ja: 'ファゴット' },
  { en: 'Clarinet', ja: 'クラリネット' },
  { en: 'Piccolo', ja: 'ピッコロ' },
  { en: 'Flute', ja: 'フルート' },
  { en: 'Recorder', ja: 'リコーダー' },
  { en: 'Pan Flute', ja: 'パンフルート' },
  { en: 'Blown Bottle', ja: 'ボトルブロー' },
  { en: 'Shakuhachi', ja: '尺八' },
  { en: 'Whistle', ja: 'ホイッスル' },
  { en: 'Ocarina', ja: 'オカリナ' },
  { en: 'Lead 1 (square)', ja: 'リード 1（矩形波）' },
  { en: 'Lead 2 (sawtooth)', ja: 'リード 2（のこぎり波）' },
  { en: 'Lead 3 (calliope)', ja: 'リード 3（カリオペ）' },
  { en: 'Lead 4 (chiff)', ja: 'リード 4（チフ）' },
  { en: 'Lead 5 (charang)', ja: 'リード 5（チャランゴ）' },
  { en: 'Lead 6 (voice)', ja: 'リード 6（ボイス）' },
  { en: 'Lead 7 (fifths)', ja: 'リード 7（フィフス）' },
  { en: 'Lead 8 (bass + lead)', ja: 'リード 8（ベース + リード）' },
  { en: 'Pad 1 (new age)', ja: 'パッド 1（ニューエイジ）' },
  { en: 'Pad 2 (warm)', ja: 'パッド 2（ウォーム）' },
  { en: 'Pad 3 (polysynth)', ja: 'パッド 3（ポリシンセ）' },
  { en: 'Pad 4 (choir)', ja: 'パッド 4（クワイア）' },
  { en: 'Pad 5 (bowed)', ja: 'パッド 5（ボウド）' },
  { en: 'Pad 6 (metallic)', ja: 'パッド 6（メタリック）' },
  { en: 'Pad 7 (halo)', ja: 'パッド 7（ハロー）' },
  { en: 'Pad 8 (sweep)', ja: 'パッド 8（スイープ）' },
  { en: 'FX 1 (rain)', ja: 'エフェクト 1（レイン）' },
  { en: 'FX 2 (soundtrack)', ja: 'エフェクト 2（サウンドトラック）' },
  { en: 'FX 3 (crystal)', ja: 'エフェクト 3（クリスタル）' },
  { en: 'FX 4 (atmosphere)', ja: 'エフェクト 4（アトモスフィア）' },
  { en: 'FX 5 (brightness)', ja: 'エフェクト 5（ブライトネス）' },
  { en: 'FX 6 (goblins)', ja: 'エフェクト 6（ゴブリン）' },
  { en: 'FX 7 (echoes)', ja: 'エフェクト 7（エコー）' },
  { en: 'FX 8 (sci-fi)', ja: 'エフェクト 8（SF）' },
  { en: 'Sitar', ja: 'シタール' },
  { en: 'Banjo', ja: 'バンジョー' },
  { en: 'Shamisen', ja: '三味線' },
  { en: 'Koto', ja: '琴' },
  { en: 'Kalimba', ja: 'カリンバ' },
  { en: 'Bag pipe', ja: 'バグパイプ' },
  { en: 'Fiddle', ja: 'フィドル' },
  { en: 'Shanai', ja: 'シャナイ' },
  { en: 'Tinkle Bell', ja: 'ティンクルベル' },
  { en: 'Agogo', ja: 'アゴゴ' },
  { en: 'Steel Drums', ja: 'スティールドラム' },
  { en: 'Woodblock', ja: 'ウッドブロック' },
  { en: 'Taiko Drum', ja: '太鼓' },
  { en: 'Melodic Tom', ja: 'メロディックタム' },
  { en: 'Synth Drum', ja: 'シンセドラム' },
  { en: 'Reverse Cymbal', ja: 'リバースシンバル' },
  { en: 'Guitar Fret Noise', ja: 'ギターのフレットノイズ' },
  { en: 'Breath Noise', ja: 'ブレスノイズ' },
  { en: 'Seashore', ja: '波の音' },
  { en: 'Bird Tweet', ja: '鳥のさえずり' },
  { en: 'Telephone Ring', ja: '電話の呼び出し音' },
  { en: 'Helicopter', ja: 'ヘリコプター' },
  { en: 'Applause', ja: '拍手' },
  { en: 'Gunshot', ja: '銃声' },
];

/**
 * The standard name for each GS insertion-effect type, keyed the same way as
 * `data/efx-tables.json`'s `defaults.by_type`.
 */
export const GS_EFX_TYPES: Readonly<Record<string, LocalizedName>> = {
  '00 00': { en: 'Thru', ja: 'スルー' },
  '01 00': { en: 'Stereo-EQ', ja: 'ステレオ EQ' },
  '01 01': { en: 'Spectrum', ja: 'スペクトラム' },
  '01 02': { en: 'Enhancer', ja: 'エンハンサー' },
  '01 03': { en: 'Humanizer', ja: 'ヒューマナイザー' },
  '01 10': { en: 'Overdrive', ja: 'オーバードライブ' },
  '01 11': { en: 'Distortion', ja: 'ディストーション' },
  '01 20': { en: 'Phaser', ja: 'フェイザー' },
  '01 21': { en: 'Auto Wah', ja: 'オートワウ' },
  '01 22': { en: 'Rotary', ja: 'ロータリー' },
  '01 23': { en: 'Stereo Flanger', ja: 'ステレオフランジャー' },
  '01 24': { en: 'Step Flanger', ja: 'ステップフランジャー' },
  '01 25': { en: 'Tremolo', ja: 'トレモロ' },
  '01 26': { en: 'Auto Pan', ja: 'オートパン' },
  '01 30': { en: 'Compressor', ja: 'コンプレッサー' },
  '01 31': { en: 'Limiter', ja: 'リミッター' },
  '01 40': { en: 'Hexa Chorus', ja: 'ヘキサコーラス' },
  '01 41': { en: 'Tremolo Chorus', ja: 'トレモロコーラス' },
  '01 42': { en: 'Stereo Chorus', ja: 'ステレオコーラス' },
  '01 43': { en: 'Space-D', ja: 'スペース D' },
  '01 44': { en: '3D Chorus', ja: '3D コーラス' },
  '01 50': { en: 'Stereo Delay', ja: 'ステレオディレイ' },
  '01 51': { en: 'Modulation Delay', ja: 'モジュレーションディレイ' },
  '01 52': { en: '3 Tap Delay', ja: '3 タップディレイ' },
  '01 53': { en: '4 Tap Delay', ja: '4 タップディレイ' },
  '01 54': { en: 'Time Control Delay', ja: 'タイムコントロールディレイ' },
  '01 55': { en: 'Reverb', ja: 'リバーブ' },
  '01 56': { en: 'Gate Reverb', ja: 'ゲートリバーブ' },
  '01 57': { en: '3D Delay', ja: '3D ディレイ' },
  '01 60': { en: '2-Voice Pitch Shifter', ja: '2 ボイスピッチシフター' },
  '01 61': { en: 'Feedback Pitch Shifter', ja: 'フィードバックピッチシフター' },
  '01 70': { en: '3D Auto', ja: '3D オート' },
  '01 71': { en: '3D Manual', ja: '3D マニュアル' },
  '01 72': { en: 'Lo-Fi 1', ja: 'ローファイ 1' },
  '01 73': { en: 'Lo-Fi 2', ja: 'ローファイ 2' },
  '02 00': { en: 'Overdrive → Chorus', ja: 'オーバードライブ → コーラス' },
  '02 01': { en: 'Overdrive → Flanger', ja: 'オーバードライブ → フランジャー' },
  '02 02': { en: 'Overdrive → Delay', ja: 'オーバードライブ → ディレイ' },
  '02 03': { en: 'Distortion → Chorus', ja: 'ディストーション → コーラス' },
  '02 04': { en: 'Distortion → Flanger', ja: 'ディストーション → フランジャー' },
  '02 05': { en: 'Distortion → Delay', ja: 'ディストーション → ディレイ' },
  '02 06': { en: 'Enhancer → Chorus', ja: 'エンハンサー → コーラス' },
  '02 07': { en: 'Enhancer → Flanger', ja: 'エンハンサー → フランジャー' },
  '02 08': { en: 'Enhancer → Delay', ja: 'エンハンサー → ディレイ' },
  '02 09': { en: 'Chorus → Delay', ja: 'コーラス → ディレイ' },
  '02 0A': { en: 'Flanger → Delay', ja: 'フランジャー → ディレイ' },
  '02 0B': { en: 'Chorus → Flanger', ja: 'コーラス → フランジャー' },
  '03 00': { en: 'Rotary Multi', ja: 'ロータリーマルチ' },
  '04 00': { en: 'Guitar Multi 1', ja: 'ギターマルチ 1' },
  '04 01': { en: 'Guitar Multi 2', ja: 'ギターマルチ 2' },
  '04 02': { en: 'Guitar Multi 3', ja: 'ギターマルチ 3' },
  '04 03': { en: 'Clean Guitar Multi 1', ja: 'クリーンギターマルチ 1' },
  '04 04': { en: 'Clean Guitar Multi 2', ja: 'クリーンギターマルチ 2' },
  '04 05': { en: 'Bass Multi', ja: 'ベースマルチ' },
  '04 06': { en: 'Rhodes Multi', ja: 'ローズマルチ' },
  '05 00': { en: 'Keyboard Multi', ja: 'キーボードマルチ' },
  '11 00': { en: 'Chorus/Delay', ja: 'コーラス / ディレイ' },
  '11 01': { en: 'Flanger/Delay', ja: 'フランジャー / ディレイ' },
  '11 02': { en: 'Chorus/Flanger', ja: 'コーラス / フランジャー' },
  '11 03': { en: 'Overdrive/Distortion 1, 2', ja: 'オーバードライブ / ディストーション 1、2' },
  '11 04': {
    en: 'Overdrive/Distortion, Rotary',
    ja: 'オーバードライブ / ディストーション、ロータリー',
  },
  '11 05': {
    en: 'Overdrive/Distortion, Phaser',
    ja: 'オーバードライブ / ディストーション、フェイザー',
  },
  '11 06': {
    en: 'Overdrive/Distortion, Auto Wah',
    ja: 'オーバードライブ / ディストーション、オートワウ',
  },
  '11 07': { en: 'Phaser, Rotary', ja: 'フェイザー、ロータリー' },
  '11 08': { en: 'Phaser, Auto Wah', ja: 'フェイザー、オートワウ' },
};

/** Keys from {@link GS_EFX_TYPES} whose name could not be confirmed. Empty: every key was confirmed. */
export const GS_EFX_TYPES_UNNAMED: readonly string[] = [];

/** The instrument family a GM program number belongs to. */
export function gmFamilyOf(program: number): LocalizedName {
  const family = GM_FAMILIES.find((f) => program >= f.first && program <= f.last);
  if (!family) throw new RangeError(`program out of range: ${program}`);
  return family.name;
}
